### ISSUE TITLE
Display sessions which take place before 11:00

### ISSUE THREAD

**Issue by iblech** [voc/schedule#61]
Currently, the 36C3 Fahrplan app doesn't display any self-organized sessions which take place before 11:00. (This does not affect talks which take place at the several alternate stages. It only affects self-organized sessions which are listed on the wiki.)

This is because schedule.py:empty_copy_of copies the start and end times of each day from the main Fahrplan schedule. But the main Fahrplan schedule declares the starting time of each day to be 11:00. (Reasonably so, since the main talks don't start before 11:00.)

I see two ways of fixing the problem:

1. Ignore the main Fahrplan day starting times.
2. Change the day starting times of the main Fahrplan schedule.

It would be great if this could be fixed so that congress newcomers, who don't yet follow the wiki closely but rely on the Fahrplan app, also have a chance of participating in the early morning sessions. Thank you for your hard work! It is very much appreciated. :-)

**Comment by saerdnaer** [comment]
should be fixed with https://github.com/voc/schedule/pull/57/commits/c00aa7a7398c7e66580f99d47d38b3127077e493

can you confirm by closing the issue?

**Comment by iblech** [comment]
This fix looks very reasonable, thank you!

Is it applied to https://github.com/voc/36C3_schedule? Because https://github.com/voc/36C3_schedule/blob/master/everything.schedule.json still doesn't list sessions which start before 11:00 (for instance, grep for `Parkour` -- you should then see https://events.ccc.de/congress/2019/wiki/index.php/Session:Parkour_-_des_Nerds_Lieblingssport%3F).

**Comment by iblech** [comment]
Thank you for the quick fix! A couple hours after my previous comment, the fix propagated to the relevant JSON files. :-)
